repos:

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: .coverage

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
#      - id: detect-aws-credentials
      - id: detect-private-key
#      - id: no-commit-to-branch
#        args: [ --branch, main, --branch, master, --pattern, release/.* ]
